spring:
  application:
    name: api-gateway
    
server:
  port: 8765
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
      
  instance:
    prefer-ip-address: true