spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: currency-exchange
        uri: lb://currency-exchange-service
        predicates:
        - Path=/currency-exchange/**
       
      - id: currency-calculation
        uri: lb://currency-calculation-service
        predicates:
        - Path=/currency-converter/**
          

    
server:
  port: 8765
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
      
  instance:
    prefer-ip-address: true
    